googleinterns/step171-2020

src/main/webapp/index.html
src/main/webapp/main_hub.html
src/main/webapp/project.html
src/main/webapp/script.js
src/main/webapp/style.css
src/main/webapp/task.html
src/main/webapp/user_profile.html

Buttons for admins, tasks, and members are added to the Project Page. CSS is used to make it formatted nicely. Feel free to change the color scheme though.

Add buttons to Project Page

---

src/main/webapp/project.html
src/main/webapp/task.html

Task Page is filled up. A few lines in the Project Page are changed.

Tzirliya development

---

src/main/webapp/style.css
src/main/webapp/user_profile.html

This is mainly a test pull request because I've been having some issues w/ GitHub and GCP   :)

Add some content to user_profile and include css

---

src/main/webapp/jsp_example/index.jsp
src/main/webapp/jsp_example/some_other_page.jsp
src/main/webapp/jsp_example/templates/content_layout.jsp
src/main/webapp/jsp_example/templates/footer_template.jsp
src/main/webapp/jsp_example/templates/header_template.jsp
src/main/webapp/jsp_example/templates/side_nav.jsp

JSP example to give you some ideas

JSP Example

---

src/main/webapp/index.html
src/main/webapp/main_hub.html
src/main/webapp/project.html
src/main/webapp/script.js
src/main/webapp/task.html
src/main/webapp/user_profile.html

Mock projects are added. More mock tasks are added. There's a "go to project" button on the Task Page. The navigation bar is updated to use JavaScript functions to redirect instead of using HTML. This allows the goToProject() and goToTask() functions to randomly choose a specific project or task instead of default values.

Add Projects

---

src/main/webapp/index.html
src/main/webapp/main_hub.html
src/main/webapp/project.html
src/main/webapp/script.js
src/main/webapp/style.css
src/main/webapp/task.html
src/main/webapp/user_profile.html
src/main/webapp/user_settings.html

Add a confirmation to edit user info (if everyone can see all user pages) and a skills section.

New features on User_Profile.

---

src/main/java/com/rtb/projectmanagementtool/user/UserData.java

Do I need a UserController type of class too where I should define the non getter/setter methods?

new user class

---

pom.xml
src/main/java/com/rtb/projectmanagementtool/taskblocker/TaskBlockerController.java
src/main/java/com/rtb/projectmanagementtool/taskblocker/TaskBlockerData.java
src/main/webapp/WEB-INF/appengine-web.xml
src/test/java/com/rtb/projectmanagementtool/taskblocker/TaskBlockerControllerTest.java
src/test/java/com/rtb/projectmanagementtool/taskblocker/TaskBlockerDataTest.java

Sample test classes with local/mock Datastore testing

---

src/main/java/com/rtb/projectmanagementtool/user/UserData.java
src/main/java/com/rtb/projectmanagementtool/user/UserServlet.java
src/test/java/com/rtb/projectmanagementtool/user/UserControllerTest.java
src/test/java/com/rtb/projectmanagementtool/user/UserDataTest.java
src/test/java/com/rtb/projectmanagementtool/user/UserServletTest.java

All tests pass. Ready for review.

UserServer Test and Implement Enums

---

pom.xml
src/main/java/com/rtb/projectmanagementtool/project/ProjectController.java
src/main/java/com/rtb/projectmanagementtool/project/ProjectData.java
src/main/java/com/rtb/projectmanagementtool/project/UserProjectRole.java
src/main/java/com/rtb/projectmanagementtool/project/servlets/DeleteProjectServlet.java
src/main/java/com/rtb/projectmanagementtool/project/servlets/DisplayProjectsServlet.java
src/main/java/com/rtb/projectmanagementtool/project/servlets/NewProjectServlet.java
src/test/java/com/rtb/projectmanagementtool/project/ProjectControllerTest.java
src/test/java/com/rtb/projectmanagementtool/project/ProjectDataTest.java
src/test/java/com/rtb/projectmanagementtool/project/servlets/DeleteProjectServletTest.java
src/test/java/com/rtb/projectmanagementtool/project/servlets/DisplayProjectsServletTest.java
src/test/java/com/rtb/projectmanagementtool/project/servlets/NewProjectServletTest.java

Created Servlets for Projects as well as accompanying tests. PR also includes improvements based on comments on previous PR

Project Servlets and Tests

---

src/main/java/com/rtb/projectmanagementtool/task/TaskController.java
src/main/java/com/rtb/projectmanagementtool/task/TaskData.java
src/main/java/com/rtb/projectmanagementtool/task/TaskServlet.java
src/test/java/com/rtb/projectmanagementtool/task/TaskControllerTest.java
src/test/java/com/rtb/projectmanagementtool/task/TaskDataTest.java
src/test/java/com/rtb/projectmanagementtool/task/TaskServletTest.java

Update Task Classes based on suggestions from the previous pull request.

Update Task Classes

---

src/main/java/com/rtb/projectmanagementtool/task/TaskController.java
src/test/java/com/rtb/projectmanagementtool/task/TaskControllerTest.java

More methods are added to TaskController, along with corresponding unit tests. Recursive functions are wrapped in a transaction.
`getTasksByUserID()` will be used by a user servlet to fetch all tasks that a user is a member of.
`getTasksByProjectID()` will be used by a project servlet to fetch all of the top-level tasks under a project.
`addUser()` will be used by a task servlet to recursively add a user to the current task and its parent tasks.
`removeUser()` will be used by a task servlet to recursively remove a user from the current task and its subtasks.

Add Methods to TaskController

---

src/main/java/com/rtb/projectmanagementtool/task/TaskAddUserServlet.java
src/main/java/com/rtb/projectmanagementtool/task/TaskRemoveUserServlet.java
src/main/java/com/rtb/projectmanagementtool/task/TaskServlet.java
src/main/webapp/add_task.html
src/main/webapp/scripts/task.js
src/main/webapp/task.html
src/test/java/com/rtb/projectmanagementtool/task/TaskAddUserServletTest.java
src/test/java/com/rtb/projectmanagementtool/task/TaskRemoveUserServletTest.java
src/test/java/com/rtb/projectmanagementtool/task/TaskServletTest.java

Servlets are added to add and remove users from tasks. Buttons are created on the task page to add or remove the users. The add task feature is updated to add parentTaskID when creating subtasks.

Add/Remove Users from Tasks

---

src/main/java/com/rtb/projectmanagementtool/task/TaskAddUserServlet.java
src/main/java/com/rtb/projectmanagementtool/task/TaskController.java
src/main/java/com/rtb/projectmanagementtool/task/TaskRemoveUserServlet.java
src/main/java/com/rtb/projectmanagementtool/task/TaskServlet.java
src/main/webapp/add-task.jsp
src/main/webapp/list-tasks.jsp
src/main/webapp/navigation-bar.jsp
src/main/webapp/task.jsp
src/test/java/com/rtb/projectmanagementtool/task/TaskServletTest.java

All of the HTML pages are converted to JSP pages, including all features present previously. A JSP page is created to insert a list of tasks. It's not part of the task page so it can be reused by other pages. 
Features: Tasks and subtasks can be added, user assignment to a task can be toggled, and buttons to return to a task's parent task and/or project are present if the task/project is found in datastore.

Convert to JSP

---

src/main/java/com/rtb/projectmanagementtool/comment/CommentController.java
src/main/java/com/rtb/projectmanagementtool/comment/CommentData.java
src/main/java/com/rtb/projectmanagementtool/init/InitTestData.java
src/main/java/com/rtb/projectmanagementtool/task/TaskController.java
src/main/java/com/rtb/projectmanagementtool/task/TaskDeleteServlet.java
src/main/webapp/task.jsp
src/test/java/com/rtb/projectmanagementtool/comment/CommentControllerTest.java
src/test/java/com/rtb/projectmanagementtool/comment/CommentDataTest.java

Suggestions from the previous pull request are implemented. CommentData.java and CommentController.java are created along with unit tests.

Create CommentData and CommentController Classes

---

src/main/java/com/rtb/projectmanagementtool/comment/CommentDeleteServlet.java
src/main/java/com/rtb/projectmanagementtool/comment/CommentServlet.java
src/main/java/com/rtb/projectmanagementtool/init/InitTestData.java
src/main/java/com/rtb/projectmanagementtool/task/TaskServlet.java
src/main/webapp/navigation-bar.jsp
src/main/webapp/style.css
src/main/webapp/task.jsp
src/test/java/com/rtb/projectmanagementtool/comment/CommentDeleteServletTest.java
src/test/java/com/rtb/projectmanagementtool/comment/CommentServletTest.java
src/test/java/com/rtb/projectmanagementtool/task/TaskDeleteServletTest.java
src/test/java/com/rtb/projectmanagementtool/task/TaskServletTest.java

Users can post comments on a Task Page. Comments are displayed on the Task Page. Users can delete their own comments from the Task Page. Users cannot add or delete comments if a task is set to COMPLETE. Servlets and unit tests are created to do these features.

Add and Delete Comments of a Task

---

src/main/java/com/rtb/projectmanagementtool/task/TaskServlet.java
src/main/webapp/add-task.jsp
src/main/webapp/project.jsp
src/main/webapp/task.jsp

Fix typos. Make a button look nice. Prevent adding subtasks when parent task is set to complete.

Fix Small Details

---

src/main/java/com/rtb/projectmanagementtool/task/TaskController.java
src/main/java/com/rtb/projectmanagementtool/task/TaskServlet.java
src/main/webapp/list-tasks.jsp
src/main/webapp/list-users.jsp
src/main/webapp/style.css
src/main/webapp/task-status-checkmark.jsp
src/main/webapp/task.jsp

At the top of the Task Page, there's links to all of its parent tasks and its parent project.
The list of user buttons displays user information better.
The status button is a checkmark that can be toggled and appears next to the task's title. Messages appear when hovering over the checkmark. The list of tasks/subtasks also contain a checkmark icon with messages when hovering, but it cannot be toggled there.

Improve user-friendliness on Task Page

---

src/main/java/com/rtb/projectmanagementtool/task/TaskController.java
src/main/java/com/rtb/projectmanagementtool/task/TaskTreeData.java
src/main/java/com/rtb/projectmanagementtool/task/TaskTreeServlet.java
src/main/webapp/project.jsp
src/main/webapp/scripts/project.js
src/main/webapp/scripts/task.js
src/main/webapp/style.css
src/main/webapp/task-tree.jsp
src/main/webapp/task.jsp
src/test/java/com/rtb/projectmanagementtool/task/TaskControllerTest.java

A Task Tree data structure is created with Java. A TaskController method is creating to load all the tasks of a project into the tree, given a projectID. A Java Servlet returns the tree. A JSP page is created to traverse the tree and build it in HTML. CSS and JavaScript is added to display the collapsible tree in a pop-up on the Project Page and the Task Page.

Create Task Tree

---

src/main/java/com/rtb/projectmanagementtool/task/TaskController.java
src/main/java/com/rtb/projectmanagementtool/task/TaskServlet.java
src/main/java/com/rtb/projectmanagementtool/taskblocker/TaskBlockerController.java
src/main/java/com/rtb/projectmanagementtool/taskblocker/TaskBlockerData.java
src/test/java/com/rtb/projectmanagementtool/taskblocker/TaskBlockerControllerTest.java

A path-finding algorithm is added to check if there will be a cycle if a TaskBlocker entity is added to datastore. Unit tests are added.
Suggestions from the previous pull request are implemented.

Add Algorithm to Check for Cycles

---

src/main/java/com/rtb/projectmanagementtool/task/TaskServlet.java

There's a bug in the deployed site that doesn't appear in the dev server, so hopefully this fixes it?

Hopefully Fix Bug
